export const productCards = [
  {
    name: "card card__mousse",
    title: "Увлажняющий мусс",
    description: "Глубоко увлажняют кожу лица, оставляя её мягкой и гладкой.",
    firstIngredient: "активные натуральные комплексы",
    secondIngredient: "витамины C, A, PP, B и E",
    thirdIngredient: "солнцезащитные компоненты",
    priceP: "2 750 &#8381",
    image: "img/moisturizing-mousse.png",
  },
  {
    name: "card card__mask",
    title: "Увлажняющая маска",
    description: "Способствует удерживанию влаги в верхних слоях кожи.",
    firstIngredient: "воски",
    secondIngredient: "минералы",
    thirdIngredient: "масла",
    priceP: "3 500 &#8381",
    image: "img/moisturizing-mask.png",
  },
  {
    name: "card card__gel",
    title: "Гель для умывания",
    description: "Интенсивно очищает, не повреждает защитный барьер кожи.",
    firstIngredient: "минералы",
    secondIngredient: "витамины C, A, PP, B и E",
    thirdIngredient: "солнцезащитные компоненты",
    priceP: "1 650 &#8381",
    image: "img/cleansing-gel.png",
  },
  {
    name: "card card__gift_set_1",
    title: "Подарочный набор №1",
    description: "Набор, состоящий из увлажняющего крема и маски.",
    firstIngredient: "воски",
    secondIngredient: "минералы",
    thirdIngredient: "масла",
    priceP: "4 750 &#8381",
    image: "img/gift-set-first.png",
  },
  {
    name: "card card__gift_set_5",
    title: "Подарочный набор №5",
    description:
      "Весь набор средств Invisible symphony, крем, маска, мусс и гель для умывания.",
    firstIngredient: "воски",
    secondIngredient: "минералы",
    thirdIngredient: "масла",
    priceP: "7 520 &#8381",
    image: "img/gift-set-fifth.png",
  },
];
